cases/urls.py
from django.urls import path

from .views import (case_detail, add_case, update_case,
                    delete_case, add_task,upload_files,
                    new_case,  pending_list, completed_list, CaseList, CaseCreateView, CategoryListView,
                    delete_cat, cat_update, cat_add, add_argument, cat_detail, file_list,
                    delete_files, task_view, task_list_view, completed, delete_task, argument_list, argument_detail, arg_update, arg_delete, case_filter, complete_case,
                    court_list, add_court, court_detail, update_court, court_delete,

                    add_session, update_session, detail_session, delete_session,bill_case,

                    add_process, edit_task,generate_process,generate_process1,list_processes,process_detail,update_process,delete_process,add_to_archives,
                    upload_archives,update_archive,archive_detail,
                    add_action_report,list_action_reports,update_action,post_action_detail,delete_action,
                    add_rep,rep_detail,update_rep,delete_rep,rep_list,
                    case_history,
                    request_file,request_list,approve_request,make_request,all_files,start_timer,case_hours,
                    add_expense,ExpenseDetailView,ExpenseListView,update_expense,delete_expense,
                    RenumerationList,approve_renumeration,request_renumeration,
                    request_client_payment,update_client_payment,client_payment_list,client_payment_detail,edit_start_timer, addpercharge, PendingExpenseListView, accept_expense, 
                    decline_expense,resend_expense,generate_invoice_total, generate_invoice_total_save,calendar,all_user_logs,all_user_logs_per_case,upload_terms_files,terms_files_list,terms_edit

                    )


app_name = "cases"


urlpatterns = [

    path('cases/list/', CaseList.as_view(), name='case_list'),
    path('calendar/', calendar, name='calendar'),
    path('cases/list/filter-cases', case_filter, name='case_filter'),




    path("cases/pending-list", pending_list, name="pending_list"),

    path("cases/completed-list", completed_list, name="completed_list"),
    ############################### ARCHIVED CASES #####################################################
    path("cases/archived_cases", add_to_archives, name="add_archive"),
    path("cases/archives/<int:pk>/archive-details", archive_detail, name="archive_detail"),
    path("cases/archives/<int:pk>/update-archive",update_archive, name="archive_update"),
    path("cases/archives/<int:pk>/upload-files",upload_archives, name="archive_upload"),

    path("cases/<int:pk>/case-detail", case_detail, name="case_detail"),
    path("cases/add-case", add_case, name="add_case"),



    path("cases/<int:pk>/case-update", update_case, name="case_update"),
    path("cases/<int:pk>/case-delete", delete_case, name="case_delete"),
    path("cases/tasks/<int:pk>/add-task", add_task, name="add_task"),
    path("cases/files/<int:pk>/add-files", upload_files, name="upload_files"),




    ############################### TERMS OF ENGAGEMENT ########################################################
    path("cases/termsofengagement/<int:pk>/add-files", upload_terms_files, name="upload_terms_files"),
    path("cases/termsofengagement/<int:pk>/list-files", terms_files_list, name="terms_files_list"),
    path("cases/termsofengagement/terms_edit", terms_edit, name="terms_edit"),



    ############################### CATEGORY ########################################################
    path("cases/category/list", CategoryListView.as_view(), name="cat_list"),
    path("cases/category/<int:pk>/update",
         cat_update, name="cat_update"),
    path("cases/category/<int:pk>/delete", delete_cat, name="cat_delete"),
    path("cases/category/add", cat_add, name="cat_add"),
    path("cases/argument/<int:pk>/add", add_argument, name="add_arg"),
    path("cases/category/<int:pk>/detail", cat_detail, name="cat_detail"),
    path("cases/<int:pk>/case-files", file_list, name="file_list"),
    path("cases/<int:pk>/delete_file", delete_files, name="delete_file"),
    path("cases/tasks/<int:pk>/list", task_view, name="task_list"),
    path("cases/tasks/<int:pk>/list-tasks", task_list_view, name="list_tasks"),
    path("cases/tasks/<int:pk>/completed", completed, name="completed"),
    path("cases/tasks/<int:pk>/delete", delete_task, name="delete_task"),
    path("cases/<int:pk>/legal_arguments/list",
         argument_list, name="argument_list"),
    path("cases/<int:pk>/legal_arguments/detail",
         argument_detail, name="argument_detail"),
    path("cases/<int:pk>/legal_arguments/update",
         arg_update, name="argument_update"),
    path("cases/<int:pk>/legal_arguments/delete",
         arg_delete, name="argument_delete"),

    path("cases/<int:pk>/case-update-status",
         complete_case, name="complete_case"),
    ########################################################## COURT ######################################################################
    path('cases/courts/list', court_list, name='court_list'),
    path('cases/courts/<int:pk>/court-detail',
         court_detail, name="court_detail"),
    path('cases/courts/<int:pk>/court-update',
         update_court, name="court_update"),
    path('cases/courts/add', add_court, name="court_add"),
    path('cases/courts/<int:pk>/court-delete',
         court_delete, name="court_delete"),

    #################################################### COURT SESSIONS #################################################################


    path('cases/court-sessions/<int:pk>/add', add_session, name="session_add"),
    path('cases/court-sessions/<int:pk>/details',
         detail_session, name="session_detail"),
    path('cases/court-sessions/<int:pk>/update',
         update_session, name="session_update"),
    path('cases/court-sessions/<int:pk>/delete',
         delete_session, name="session_delete"),


    ############################################### PROCESSES ####################################
    path('cases/processes/add', add_process, name="process_add"),
    path('cases/processes/list', list_processes, name="list_process"),

    path('cases/processes/<int:pk>/generate-process', generate_process1, name="generate_process"),
    path('cases/processes/<int:pk>/process-detail', process_detail, name="process_detail"),
    path('cases/processes/<int:pk>/process-update', update_process, name="process_update"),
    path('cases/processes/<int:pk>/delete-process', delete_process, name="process_delete"),



    ############################################### BILL CASE ####################################
    path('cases/<int:pk>/bill-case',bill_case,name='bill_case'),

    path('cases/tasks/<int:pk>/edit-task',edit_task,name='edit_task'),

    ############################################### POST ACTION REPORT ##########################
    path('cases/post-action-report/<int:pk>/add-new',add_action_report,name="add_action"),
    path('cases/post-action-report/<int:pk>/report-list',list_action_reports,name='list_report'),
    path('cases/post-action-report/<int:pk>/report-detail',post_action_detail,name="action_detail"),
    path('cases/post-action-report/<int:pk>/update-report',update_action,name='action_update'),
    path('cases/post-action-report/<int:pk>/delete-report',delete_action,name='action_delete'),

##################################### REPRESENTATION ############################################
    path('cases/representation/add',add_rep,name="add_rep"),
    path('cases/representation/list',rep_list,name="rep_list"),
    path('cases/representation/<int:pk>/details',rep_detail,name="rep_detail"),
    path('cases/representation/<int:pk>/update',update_rep,name="update_rep"),
    path('cases/representation/<int:pk>/delete',delete_rep,name="delete_rep"),
    path("cases/<int:pk>/case-history",case_history,name='case_history'),



    ################################### ARCHIVE REQUESTS #########################################
    path('cases/archives/request',request_file,name='request_file'),
    path('cases/archives/requests/list',request_list,name='request_list'),
    path('cases/archives/<int:pk>/request',make_request,name='make_request'),
    path('cases/archives/<int:pk>/request/approve',approve_request,name='approve_request'),

    ################################### CASE FILES ###############################################
    path('cases/files/all-files',all_files,name="all_files"),
    path('cases/start-timer',start_timer,name="start_timers"),
    path('cases/edit_start_timer',edit_start_timer,name="edit_start_timer"),
    path('cases/<int:pk>/timer/elapsed-time',case_hours,name="case_hours"),
    path('cases/addpercharge',addpercharge,name="addpercharge"),
    path('cases/delete_case/<int:pk>',delete_case,name="delete_case"),


     ################################## EXPENSES #################################################
    path('cases/expenses/', ExpenseListView.as_view(), name='expenses'),
    path('cases/pending_expenses/', PendingExpenseListView.as_view(), name='pending_expenses'),
    path('cases/expenses/<int:pk>/detail', ExpenseDetailView.as_view(), name='expense_detail'),
    path('cases/expenses/<int:pk>/update', update_expense, name='update_expense'),
    path('cases/expenses/<int:pk>/delete', delete_expense, name='delete_expense'),
    path('cases/expenses/add-expense',add_expense,name='add_expense'),
    path('cases/accept_expense/<int:pk>',accept_expense,name='accept_expense'),
    path('cases/decline_expense/<int:pk>',decline_expense,name='decline_expense'),
    path('cases/resend_expense/<int:pk>',resend_expense,name='resend_expense'),

    ################################### Renumeration #############################################
    path('case/renumeration/list',RenumerationList.as_view(),name='renumerations'),
    path('case/renumeration/<int:pk>/approve',approve_renumeration,name='approve_renumeration'),

firm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, FirmChart,user_path,my_notifications,my_custom_page_not_found_view,mark_as_deleted,mark_as_read,mark_as_unread,user_logs,all_read,all_unread,account_dash,go_to_target, view_team_logs
# from ajax_select import urls
# from ajax_select import urls as ajax_select_url
from ajax_select import urls as ajax_select_urls


admin.autodiscover()

handler404 = 'firm.views.my_custom_page_not_found_view'

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", index, name="index"),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/chart/data", FirmChart.as_view(), name="api-data"),
    path("user_path/redirect/", user_path, name="user_path"),
    path("user-notifications/", my_notifications, name="user_notifications"),
    path("go_to_target/<int:pk>", go_to_target, name="go_to_target"),
    path("", include('accounts.urls')),
    path("", include('cases.urls')),
    path("", include('documents.urls')),
    path("", include('principles.urls')),
    path("", include('clients.urls')),
    path("", include('schedules.urls')),
    path("", include('visitors.urls')),
    path("", include('wills.urls')),
    path("", include('correspondents.urls')),
    path('comment/', include('comment.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('notifications/', include('notify.urls', 'notifications')),
    path("resources/", include('resources.urls')),
    path("activity/<int:pk>/user-logs",user_logs,name='user-logs'),
    path('ajax_select/', include(ajax_select_urls)),
    path('user-notifications/<int:pk>/read',mark_as_read,name="read"),
    path('user-notifications/<int:pk>/unread',mark_as_unread,name="unread"),
    path('user-notifications/all-read',all_read,name="all_read"),
    path('user-notifications/all-unread',all_unread,name="all_unread"),
    path("account_dash/",account_dash,name='account_dash'),
    path("view_team_logs/",view_team_logs,name='view_team_logs'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),







]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/cases/category/add.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}
Update Category
{% endblock title %}



{% block content %}

{% include 'messages/messages.html' %}


<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Firm</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Category</a></li>
                            <li class="breadcrumb-item active">Update</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-secondary">Save changes</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

templates/cases/category/detail.html
{% extends 'base.html' %}

{% load static %}
{% load auth_extras %}
{% block title %}
Category Details
{% load crispy_forms_tags %}
{% endblock title %}



{% block content %}
<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Lawyer System.</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'cases:cat_list' %}">Category</a>
                            </li>
                            <li class="breadcrumb-item active">Category Details</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->
        {% include 'messages/messages.html' %}









        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="mt-0 header-title text-center">
                            {{cat.name|title}}
                        </h2>
                        <p class="text-muted text-center">{{cat.date_added|date}}

                        </p>
                        {% if subs %}
<p class="text-muted text-center">
                        {% for sub in subs %}


                        <a href="{{sub.get_absolute_url}}">{{sub.name}} ,</a>

                        {% endfor %}

                         </p>
                        {% endif %}
                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->

                <div class="card">

                    <div class="card-body">




                        <!-- <button class="btn btn-gradient-primary px-4 float-right mt-0 mb-3" data-toggle="modal"
                            data-target=".bd-example-modal-xl"><i class="mdi mdi-plus-circle-outline mr-2"></i>Add New
                            Case</button>
                        <button class="btn btn-gradient-primary px-4 float-left mt-0 mb-3" data-toggle="modal"
                            data-target=".bd-example-modal-lg"><i class="mdi mdi-send mr-2"></i>Request Files</button> -->






                        <div class="table-responsive dash-social">
                            <table id="datatable" class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>Team</th>
                                        <th>Status</th>
                                        <th>Date Added</th>
                                        <th>Added By</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>


                                <!-- load -->


                                <tbody>

                                    {% for case  in  case_list %}
                                    <tr>

                                        <td>{{forloop.counter}}</td>
                                        <td>
                                            {{case.name|title}}

                                        <td>{{case.team}}</td>


                                        {% if case.closed %}
                                        <td> <span class="badge badge-md   badge-soft-success">Closed</span>
                                        </td>
                                        {% else %}
                                        <td> <span class="badge badge-md   badge-soft-danger">Open</span>
                                        </td>
                                        {% endif %}


                                        <td> {{case.date_added|date}} | {{case.date_added|timesince}} Ago</td>
                                        <td>{{case.added_by|title}}</td>



                                        <td>

                                            <a href="{{case.get_absolute_url}}"
                                                class="btn btn-gradient-secondary waves-effect waves-light"><i
                                                    class="mdi mdi-eye"></i></a>


 {% comment %} {% if request.user|has_group:"Lawyer" %}
                                            <a href="{% url 'cases:make_request' case.pk %}"
                                                class="btn btn-gradient-dark waves-effect waves-light"><i
                                                    class="mdi mdi-send"></i></a>
{% endif %} {% endcomment %}

                                        </td>


                                    </tr>



                                    {% endfor %}



                                    <!--end tr-->




                                </tbody>
                            </table>
                        </div>


                    </div>















                    </div>
            </div>


            <!--end col-->


            <div class="col-md-12 col-lg-4">
                <div class="card">
                    <div class="card-body">


                        <center>
                            <h3>Actions</h3>

                        </center>

                        <button class="btn btn-primary" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-lg">Edit</button>


                        <button class="btn btn-danger" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-center">Delete</button>

                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->
            </div>



            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0 text text-center" id="myLargeModalLabel">Edit
                                doc</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <div class="modal-body">

                            {% include 'cases/category/update.html' %}

                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>




            <div class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
                aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0" id="exampleModalLabel">Delete</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>AreYou Sure You Want TO Delete {{case.name|title}}</p>


                            <form action="{% url 'cases:cat_delete' cat.pk %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-secondary" data-dismiss="modal"
                                    aria-label="Close">Cancel</button>

                                <input type="submit" value="Delete" class="btn btn-danger">
                            </form>


                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>

        </div>
    </div>
    </div>
    {% endblock content %}

templates/cases/category/update.html
{% load crispy_forms_tags %}

<form action="{% url 'cases:cat_update' cat.pk %}" method="post">
    {% csrf_token %}
    {{cat_form|crispy}}
    {{cat_form.errors}}

    <button type="submit" class="btn btn-secondary">Update</button>
</form>