clients/urls.py
from django.urls import path
from .views import (client_create_view, client_delete,
                    client_detail, client_list,
                    client_detail, client_update,
                    cat_delete, cat_detail,
                    category_list, add_cat,
                    update_cat,
                    client_cat,add_case,
                    add_will,
                    add_engagement,update_terms,
                    delete_terms,term_detail,payment_detail,
                    add_payment,update_payment,delete_payment,payment_list,
                    type_list,type_detail,add_types,update_type,type_delete,client_type

                    )


app_name = 'clients'

urlpatterns = [

    path("clients/client_list", client_list, name='client_list'),
    path("clients/<int:pk>/client-detail", client_detail, name="client_detail"),
    path("clients/<int:pk>/client-update", client_update, name="client_update"),
    path("clients/<int:pk>/client-delete", client_delete, name="client_delete"),
    path("clients/add-client", client_create_view, name="client_add"),

    path("clients/categroy/<int:pk>/category-details",
         cat_detail, name="cat_detail"),
    path("clients/categroy/<int:pk>/category-update",
         update_cat, name="cat_update"),
    path("clients/categroy/<int:pk>/category-delete",
         cat_delete, name="cat_delete"),
    path("clients/categroy/add-category", add_cat, name="cat_add"),
    path("clients/categroy/list", category_list, name="cat_list"),
    path("clients/clients/categroy/<int:pk>/list",
         client_cat, name="client_cat"),

    #case
    path('clients/<int:pk>/add-new-case',add_case,name='add-case'),
    #will
    path('clients/<int:pk>/add-new-will',add_will,name='add-will'),


    # client types
    path("clients/type/list", type_list, name="type_list"),
    path("clients/type/<int:pk>/type-details",
         type_detail, name="type_detail"),
    path("clients/type/<int:pk>/type-update",
         update_type, name="update_type"),
    path("clients/type/<int:pk>/type-delete",
         type_delete, name="type_delete"),
    path("clients/type/add-type", add_types, name="add_types"),

    path("clients/clients/type/<int:pk>/list",
         client_type, name="client_type"),



    ####################################TERMS OF ENGAGEMENT ###############################################
    path('client/add/<int:pk>/terms-of-engagement',add_engagement,name='add_terms'),
    path('client/update/<int:pk>/terms-of-engagement',update_terms,name='update_terms'),
    path('client/details/<int:pk>/terms-of-engagement',term_detail,name='terms_detail'),
    path('client/delete/<int:pk>/terms-of-engagement',delete_terms,name='delete_terms'),


    ########################################## PAYMENTS ###################################################
    path('client/payments/list',payment_list, name='payment_list'),
    path('client/payments/add/new-payment',add_payment, name='add_payment'),
    path('client/payments/<int:pk>/details',payment_detail, name='payment_detail'),
    path('client/payments/<int:pk>/update',update_payment, name='update_payment'),
    path('client/payments/<int:pk>/delete',delete_payment, name='delete_payment'),




]

firm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, FirmChart,user_path,my_notifications,my_custom_page_not_found_view,mark_as_deleted,mark_as_read,mark_as_unread,user_logs,all_read,all_unread,account_dash,go_to_target, view_team_logs
# from ajax_select import urls
# from ajax_select import urls as ajax_select_url
from ajax_select import urls as ajax_select_urls


admin.autodiscover()

handler404 = 'firm.views.my_custom_page_not_found_view'

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", index, name="index"),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/chart/data", FirmChart.as_view(), name="api-data"),
    path("user_path/redirect/", user_path, name="user_path"),
    path("user-notifications/", my_notifications, name="user_notifications"),
    path("go_to_target/<int:pk>", go_to_target, name="go_to_target"),
    path("", include('accounts.urls')),
    path("", include('cases.urls')),
    path("", include('documents.urls')),
    path("", include('principles.urls')),
    path("", include('clients.urls')),
    path("", include('schedules.urls')),
    path("", include('visitors.urls')),
    path("", include('wills.urls')),
    path("", include('correspondents.urls')),
    path('comment/', include('comment.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('notifications/', include('notify.urls', 'notifications')),
    path("resources/", include('resources.urls')),
    path("activity/<int:pk>/user-logs",user_logs,name='user-logs'),
    path('ajax_select/', include(ajax_select_urls)),
    path('user-notifications/<int:pk>/read',mark_as_read,name="read"),
    path('user-notifications/<int:pk>/unread',mark_as_unread,name="unread"),
    path('user-notifications/all-read',all_read,name="all_read"),
    path('user-notifications/all-unread',all_unread,name="all_unread"),
    path("account_dash/",account_dash,name='account_dash'),
    path("view_team_logs/",view_team_logs,name='view_team_logs'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),







]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

wills/urls.py
from django.urls import path
from .views import (will_list, will_detail,
                    will_update,
                    add_will, delete_will, add_agreement,
                    agreement_update, agreement_detail,
                    delete_agreement, agreement_list, cat_detail, cat_list, cat_delete, add_cat, update_cat)

app_name = "wills"


urlpatterns = [
    path('wills/list', will_list, name="will_list"),
    path('will/add', add_will, name='add'),
    path('will/<int:pk>/detail', will_detail, name='details'),
    path('will/<int:pk>/update', will_update, name='update'),
    path('will/<int:pk>/deletee', delete_will, name='delete'),
    ###################################### AGREEMENTS ###################################
    path('agreements/list', agreement_list, name="agreement_list"),
    path('agreements/<int:pk>/detail', agreement_detail, name='agreement_detail'),
    path('agreements/<int:pk>/update', agreement_update, name='agreement_update'),
    path('agreements/<int:pk>/delete', delete_agreement, name='agreement_delete'),
    path('agreements/add', add_agreement, name='add_agreement'),

    #################################### ARGREEMENT CATEGORY ############################
    path("wills/categroy/<int:pk>/category-details",
         cat_detail, name="cat_detail"),
    path("wills/categroy/<int:pk>/category-update",
         update_cat, name="cat_update"),
    path("wills/categroy/<int:pk>/category-delete",
         cat_delete, name="cat_delete"),
    path("wills/categroy/add-category", add_cat, name="cat_add"),
    path("wills/categroy/list", cat_list, name="cat_list"),














]

wills/forms.py
from django import forms
from .models import Will, Agreement, AgreementCategory
from lawyers.models import Lawyer
from clients.models import Client


class DateInput(forms.DateInput):

    input_type = 'date'
    # date_field=forms.DateField(widget=DateInput)


class WillForm(forms.ModelForm):
    """WillForm definition."""
    date_of_execution = forms.DateField(
        widget=DateInput, required=False)
    date_deposited = forms.DateField(widget=DateInput)
    client=forms.ModelChoiceField(widget=forms.Select(attrs={'id':'e3','class':'form-control',}),queryset=Client.objects.all() )
    user = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(
            attrs={'id':'e1','class':'form-control' }),required=True,help_text="Please Select Lawyers From The List" ,queryset=Lawyer.objects.all())

    class Meta:
        model = Will
        fields = ['client', 'user', 'date_of_execution', 'date_deposited',
                  'receipt_number', 'court', 'internal_depository']

    # TODO: Define form fields here


class AgreementForm(forms.ModelForm):
    """WillForm definition."""
    date_of_execution = forms.DateField(widget=DateInput, required=False)
    date_of_registration = forms.DateField(widget=DateInput)


    class Meta:
        model = Agreement
        exclude = ('user',)


class AgreementCategoryForm(forms.ModelForm):

    class Meta:
        model = AgreementCategory
        fields = ('__all__')

wills/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Will, Agreement, AgreementCategory
from .forms import WillForm, AgreementForm, AgreementCategoryForm
from django.urls import reverse
# Create your views here.
from .models import models
from .forms import WillForm
from django.contrib.auth.decorators import login_required


def will_list(request):
    wills = Will.objects.filter(user__user=request.user)
    form = WillForm(request.POST or None)

    context = {
        'wills': wills,
        'form': form
    }
    return render(request, 'wills/list.html', context)
    


def will_detail(request, pk):
    will = get_object_or_404(Will, pk=pk)
    form = WillForm(request.POST or None, instance=will)
    lawyers=will.user.all()
    print(lawyers)

    context = {
        'will': will,
        'form': form,
        'lawyers':lawyers
    }

    return render(request, 'wills/detail.html', context)


def will_update(request, pk):
    will = get_object_or_404(Will, pk=pk)

    if request.method == "POST":
        form = WillForm(request.POST or None, instance=will)
        if form.is_valid():
            # form.instance.user = request.user
            form.save()
            messages.success(request, "Will Has been updated")

            return HttpResponseRedirect(reverse('wills:details', args=[will.id]))

        else:
            messages.error(
                request, "Failed to update will, please check the form")
            return HttpResponseRedirect(reverse('wills:details', args=[will.id]))

    else:
        form = WillForm()

    context = {
        'will': will,
        'form': form
    }

    return render(request, 'wills/detail.html', context)


def add_will(request):

    if request.method == "POST":
        form = WillForm(request.POST or None)
        if form.is_valid():
            # form.instance.user = request.user

            form.save()

            messages.success(request, "will has been added")
            return redirect('wills:will_list')
        else:
            messages.error(request, form.errors)
            return redirect('wills:will_list')

    else:
        form = WillForm()

    return render(request, 'wills/list.html', {'form': form})


def delete_will(request, pk):
    will = get_object_or_404(Will, pk=pk)

    if request.method == "POST":
        will.delete()
        messages.success(request, "Will Has been deleted")
        return redirect('wills:will_list')
    else:
        messages.error(request, "Willcould not deleted")
        return HttpResponseRedirect(reverse('wills:detail', args=[will.pk]))

    return render(request, 'wills/detail.html')


def agreement_list(request):
    object_list = Agreement.objects.filter(user=request.user)
    form = AgreementForm(request.POST or None)

    context = {
        'object_list': object_list,
        'form': form
    }

    return render(request, 'wills/agreements/list.html', context)


def add_agreement(request):
    if request.method == "POST":
        form = AgreementForm(request.POST or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, "Agreement has been added")
            return redirect('wills:agreement_list')
        else:
            messages.error(
                request,form.errors)
            return redirect('wills:agreement_list')
    else:
        form = AgreementForm()

    return render(request, "wills/agreements/list.html", {'form': form})


def agreement_detail(request, pk):
    object = get_object_or_404(Agreement, pk=pk)
    form = AgreementForm(request.POST or None, instance=object)

    context = {
        'agreement': object,
        'form': form
    }

    return render(request, 'wills/agreements/detail.html', context)


def agreement_update(request, pk):
    object = get_object_or_404(Agreement, pk=pk)
    if request.method == "POST":
        form = AgreementForm(request.POST or None, instance=object)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, "Agreement has been updated")
            return HttpResponseRedirect(reverse('wills:agreement_detail', args=[object.pk]))
        else:
            messages.error(request, "Agreement could not be updated")
            return HttpResponseRedirect(reverse('wills:agreement_detail', args=[object.pk]))

    else:
        form = AgreementForm()

    return render(request, 'wills/agreements/detail.html', {'form': form})


def delete_agreement(request, pk):
    object = get_object_or_404(Agreement, pk=pk)

    if request.method == "POST":
        object.delete()
        messages.success(request, "Agreement  Has been deleted")
        return redirect('wills:agreement_list')
    else:
        messages.error(request, "Agreement could not deleted")
        return HttpResponseRedirect(reverse('wills:agreement_detail', args=[object.pk]))

    return render(request, 'wills/detail.html')


@login_required
def cat_list(request):
    cats = AgreementCategory.objects.all()
    form = AgreementCategoryForm()

    context = {
        'cats': cats,
        'form': form
    }
    return render(request, 'wills/category/cat_list.html', context)


@login_required
def cat_detail(request, pk):
    cat = get_object_or_404(AgreementCategory, pk=pk)

    context = {
        'cat': cat,
        'form': AgreementCategoryForm(request.POST or None, instance=cat)
    }

    return render(request, 'wills/category/cat_detail.html', context)


@login_required
def add_cat(request):
    if request.method == "POST":
        form = AgreementCategoryForm(request.POST or None)

        if form.is_valid():
            form.save()
            messages.success(request, "Category has been added")
            return redirect('wills:cat_list')
    else:
        form = AgreementCategoryForm()

    return render(request, 'wills/category/cat_list.html', {'form': form})


@login_required
def update_cat(request, pk):
    cat = get_object_or_404(AgreementCategory, pk=pk)

    if request.method == "POST":
        form = AgreementCategoryForm(request.POST or None, instance=cat)
        if form.is_valid():
            form.save()
            messages.success(request, "Category has been updated")
            return HttpResponseRedirect(reverse('wills:cat_detail', args=[cat.pk]))
        else:
            messages.error(request, "Category could not updated")
            return HttpResponseRedirect(reverse('wills:cat_detail', args=[cat.pk]))
    else:
        form = AgreementCategoryForm()

    return render(request, "wills/category/cat_detail.html", {'form': form})


@login_required
def cat_delete(request, pk):
    cat = get_object_or_404(AgreementCategory, pk=pk)
    if request.method == "POST":
        cat.delete()
        messages.success(request, "Category has been deleted")
        return redirect('wills:cat_list')
    else:
        messages.error(request, "Category could not deleted")
        return HttpResponseRedirect(reverse('wills:cat_detail', args=[cat.pk]))

    return render(request, 'wills/category/cat_detail.html')

# @login_required
# def client_cat(request, pk):
#     cat = get_object_or_404(AgreementCategory, pk=pk)
#     # client = Client.objects.filter(category=cat)

#     context = {
#         # 'client_list': client
#     }

#     return render(request, 'wills/category/client_list.html', context)

templates/wills/category/cat_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
Category Details
{% endblock title %}



{% block content %}
<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Lawyer System.</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'wills:cat_list' %}">Category List</a>
                            </li>
                            <li class="breadcrumb-item active">Category Details</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->
        {% include 'messages/messages.html' %}









        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="mt-0 header-title text-center">
                            {{cat.title|title}}
                        </h2>
                        <p class="text-muted text-center">{{cat.date_modified}}

                        </p>






                        <!-- <div class="card shadow-none border mb-1">
                                    <div class="card-header" id="headingThree">
                                        <h5 class="my-0">
                                            <button class="btn btn-link collapsed ml-4 shadow-none" type="button"
                                                data-toggle="collapse" data-target="#collapseThree"
                                                aria-expanded="false" aria-controls="collapseThree">
                                                Attachments
                                            </button>
                                        </h5>
                                    </div>
                                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                                        data-parent="#accordionExample-faq">


                                        <div class="card-body">
                                            <div class="file-box-content">
                                                <div class="file-box">
                                                    <a href="{{doc.attachments.url}}" class="download-icon-link">
                                                        <i class="dripicons-download file-download-icon"></i>
                                                    </a>
                                                    <div class="text-center">
                                                        <i class="far fa-file-alt text-primary"></i>
                                                        <h6 class="text-truncate">{{doc.attachments}}</h6>

                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                </div> -->
                        <!-- </div> -->





                        <!--end row-->
                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->
            </div>
            <!--end col-->


            <div class="col-md-12 col-lg-4">
                <div class="card">
                    <div class="card-body">


                        <button class="btn btn-primary" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-lg">Edit</button>

                        {% if user.is_superuser %}
                        <button class="btn btn-danger" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-center">Delete</button>
                        {% endif %}
                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->
            </div>



            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0 text text-center" id="myLargeModalLabel">Edit</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <div class="modal-body">



                            <form action="{% url 'wills:cat_update' cat.pk %}" method="post">
                                {% csrf_token %}
                                {{form|crispy}}
                                {{form.erorrs}}



                                <center>
                                    <button type="submit" class="btn btn-secondary">Update</button>



                                    <button type="button" class="btn btn-danger waves-effect"
                                        data-dismiss="modal">Close</button>
                                </center>


                            </form>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>




            <div class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
                aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0" id="exampleModalLabel">Delete </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>AreYou Sure You Want To Delete {{cat.title|title}}</p>


                            <form action="{% url 'wills:cat_delete' cat.pk %}" method="POST">
                                {% csrf_token %}


                                <center>
                                    <button type="submit" class="btn btn-danger">Delete</button>

                                    <button type="button" class="btn btn-secondary waves-effect"
                                        data-dismiss="modal">Close</button>

                                </center>

                            </form>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>

        </div>
    </div>
    {% endblock content %}

templates/wills/category/cat_list.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% load crispy_forms_tags %}
{% block title %}
Agreement Category List


{% endblock title %}

{% block content %}


<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Lawyer System.</a></li>

                            </li>
                            <li class="breadcrumb-item active">Category List</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->

        {% include 'messages/messages.html' %}








        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-body">
                        <button class="btn btn-gradient-primary px-4 float-right mt-0 mb-3" data-toggle="modal"
                            data-target=".bd-example-modal-xl"><i class="mdi mdi-plus-circle-outline mr-2"></i>Add New
                            Category</button>

                        <h4 class="mt-0 header-title">Category List</h4>

                        <div class="table-responsive dash-social">
                            <table id="datatable" class="table">
                                <thead>
                                    <tr>

                                        <th>Category</th>
                                        <th>Last Modified</th>

                                        <th>Action</th>

                                    </tr>
                                </thead>


                                <!-- load -->


                                <tbody>

                                    {% for cat in  cats %}
                                    <tr>


                                        <td> <a href="{% url 'clients:client_cat' cat.pk %}">{{cat.title|title}}</a>
                                        </td>





                                        <td> {{cat.date_modified|timesince}} Ago</td>




                                        <td>

                                            <a href="{% url 'wills:cat_detail' cat.pk %}"
                                                class="btn btn-gradient-secondary waves-effect waves-light"><i
                                                    class="mdi mdi-eye"></i></a>






                                        </td>

                                    </tr>



                                    {% endfor %}



                                    <!--end tr-->




                                </tbody>
                            </table>
                        </div>


                    </div>













                    <!-- sample modal content -->
                    <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-xl">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title mt-0" id="myModalLabel">New Category</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">×</button>
                                </div>
                                <div class="modal-body">

                                    <form action="{% url 'wills:cat_add' %}" method="post">
                                        {% csrf_token %}
                                        {{form|crispy}}


                                        <center>
                                            <button type="submit" class="btn btn-secondary">Add Category</button>
                                            <button type="button" class="btn btn-danger waves-effect"
                                                data-dismiss="modal">Close</button>


                                        </center>


                                    </form>

                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->













                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

    {% endblock content %}