accounts/urls.py
from django.urls import path
from .views import (accounts, update_lawyers_profile, staff_detail_view,
                    lawyer_profile_view, lawyer_detail, lawyer_list,
                    lawyer_profile, other_staff, update_lawyer_profile,
                    change_password, add_staff, staff_details,
                    update_staff, update_staff_profile, delete_lawyer, delete_staff,
                    client_dashboard,get_case_details ,team_list_view,add_team,
                    update_team,team_detail,team_update,delete_team,
                    add_role,role_detail,role_list,update_role,delete_role,
                    status_list,add_status,delete_status,update_status,status_detail,case_detail_acc,get_case_expenses,AccountExpense, account_expense,
                    invoice_list,invoice_detail,approve_invoice





                    )


app_name = "accounts"


urlpatterns = [

    path("accounts/signup", accounts, name="signup"),
    path("accounts/lawyer/signup", lawyer_profile_view, name='lawyer-signup'),
    path("accounts/lawyers/lawyer-list", lawyer_list, name="lawyer_list"),
    path("accounts/lawyers/<int:pk>/lawyer-detail",
         lawyer_detail, name="lawyer_detail"),


    path("accounts/lawyers/<int:pk>/lawyer-profile",
         lawyer_profile, name="lawyer_profile"),

    path("accounts/front-desk/staff-list", other_staff, name="staff_list"),
    path("accounts/password", change_password, name="change_password"),
    path("accounts/users/add-staff", add_staff, name="add_staff"),
    path("accounts/users/<int:pk>/staff-detail",
         staff_details, name='staff_detail'),
    path("accounts/users/<int:pk>/update-staff",
         update_staff, name='update_staff'),

    path("accounts/lawyers/<int:pk>/lawyers-profile",
         update_lawyers_profile, name="lawyers_profile"),







    path("accounts/profile/<int:pk>/update-profile",
         update_lawyer_profile, name="update_profile"),
    path("accounts/<int:pk>/profile/staff-profile",
         staff_detail_view, name="staff_profile"),


    path("accounts/profile/<int:pk>/update-staff-profile",
         update_staff_profile, name="staff_profileupdate"),

    path("accounts/lawyers/<int:pk>/delete",
         delete_lawyer, name="delete_lawyer"),
    path("accounts/staff/<int:pk>/delete", delete_staff, name="delete_staff"),

    ######################### CLIENTS ###############################################


    path("accounts/clients/<int:pk>/client-dashboard",client_dashboard,name="client_dashboard"),
    path("accounts/clients/<int:pk>/case-detail",get_case_details, name="case_details"),

    ############################################ TEAMS ##################################################

    path("accounts/teams/team-list",team_list_view,name='teams'),
    path("accounts/teams/add-team",add_team,name="add_team"),
    path("accounts/teams/<int:pk>/team/detail",team_detail,name="team_detail"),
    path("accounts/teams/<int:pk>/team/delete",delete_team, name="team_delete"),
    path("accounts/teams/<int:pk>/team/update",team_update,name="team_update"),
    path("accounts/teams/<int:pk>/team/update",update_team,name="update_team"),


    ############################# ROLES #######################################
    path("accounts/roles/roles-list",role_list,name='role_list'),
    path("accounts/roles/add-role",add_role,name='add_role'),

    path("accounts/roles/<int:pk>/role-details",role_detail,name="role_detail"),
    path("accounts/roles/<int:pk>/update-role",update_role,name="update_role"),
    path("accounts/roles/<int:pk>/delete-role",delete_role,name="delete_role"),


    ############################ Lawyer Status ###############################

    path("accounts/status/status-list",status_list,name='status_list'),
    path("accounts/expenses",account_expense,name='expenses'),
    path("accounts/status/add-status",add_status,name='add_status'),
    path("accounts/status/<int:pk>/status-details",status_detail,name="status_detail"),
    path("accounts/status/<int:pk>/update-status",update_status,name="update_status"),
    path("accounts/status/<int:pk>/delete-status",delete_status,name="delete_status"),
    path("accounts/cases/<int:pk>/detail",case_detail_acc,name='case_detail_acc'),
    path("accounts/cases/<int:pk>/case-expenses",get_case_expenses,name='case_expenses'),



     # invoice
     
    path("accounts/invoice_list/",invoice_list,name='invoice_list'),
    path("accounts/invoice_detail/<int:pk>",invoice_detail,name='invoice_detail'),
    path("accounts/approve_invoice/<int:pk>",approve_invoice,name='approve_invoice'),







]

firm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, FirmChart,user_path,my_notifications,my_custom_page_not_found_view,mark_as_deleted,mark_as_read,mark_as_unread,user_logs,all_read,all_unread,account_dash,go_to_target, view_team_logs
# from ajax_select import urls
# from ajax_select import urls as ajax_select_url
from ajax_select import urls as ajax_select_urls


admin.autodiscover()

handler404 = 'firm.views.my_custom_page_not_found_view'

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", index, name="index"),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/chart/data", FirmChart.as_view(), name="api-data"),
    path("user_path/redirect/", user_path, name="user_path"),
    path("user-notifications/", my_notifications, name="user_notifications"),
    path("go_to_target/<int:pk>", go_to_target, name="go_to_target"),
    path("", include('accounts.urls')),
    path("", include('cases.urls')),
    path("", include('documents.urls')),
    path("", include('principles.urls')),
    path("", include('clients.urls')),
    path("", include('schedules.urls')),
    path("", include('visitors.urls')),
    path("", include('wills.urls')),
    path("", include('correspondents.urls')),
    path('comment/', include('comment.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('notifications/', include('notify.urls', 'notifications')),
    path("resources/", include('resources.urls')),
    path("activity/<int:pk>/user-logs",user_logs,name='user-logs'),
    path('ajax_select/', include(ajax_select_urls)),
    path('user-notifications/<int:pk>/read',mark_as_read,name="read"),
    path('user-notifications/<int:pk>/unread',mark_as_unread,name="unread"),
    path('user-notifications/all-read',all_read,name="all_read"),
    path('user-notifications/all-unread',all_unread,name="all_unread"),
    path("account_dash/",account_dash,name='account_dash'),
    path("view_team_logs/",view_team_logs,name='view_team_logs'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),







]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from lawyers.models import Lawyer, OtherStaff, User,Team,Role,LawyerStatus
from .forms import UserForm, OtherStaffForm, LawyerForm, OtherStaffForm, UpdateUserForm, UpdateForm, StaffUpdateForm, StaffProfileForm, LawyerProfileForm,TeamForm,RoleForm,LawyerStatusForm
from django.contrib import messages
from django.contrib.auth import login, authenticate
# Create your views here.
from django.contrib.auth import update_session_auth_hash
from clients.models import Client
from django.contrib.auth.models import Group
from cases.user_actions import log_deletion,log_change,add_log

from django.views.generic import ListView,DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from cases.models import Case, Status,Bill,CourtSession,EngagementTerm,Expense,Invoice,TermsOfEngagement
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import PasswordChangeForm
from .decorators import group_required, groups_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from documents.models import DocumentRecord, Document, DocumentStatus
from cases.forms import CaseForms
from principles.forms import PrinciplesForm
from lawyers.models import Team
from django.db.models import Sum
from django.db.models import Q
from django.contrib.admin.models import LogEntry


@login_required
def accounts(request):
    lawyer_form = LawyerForm()
    user_form = UserForm()

    context = {
        'lawyer_form': lawyer_form,
        'user_form': user_form,
    }

    return render(request, 'accounts/signup.html', context)


@login_required
def lawyer_profile_view(request):

    if request.method == 'POST':
        user_form = UserForm(request.POST or None)
        lawyer_form = LawyerForm(request.POST or None)

        if user_form.is_valid() and lawyer_form.is_valid():
            team=user_form.cleaned_data['team']

            user = user_form.save(commit=False)
            add_log(request.user.pk,user,"added a lawyer")
            email = user_form.cleaned_data.get('email')
            password = user_form.cleaned_data.get('password1')
            email = user_form.cleaned_data.get('email')
            user.set_password(password)
            user.save()
            # user = authenticate(request, username=email, password=password)




            my_group = Group.objects.get(pk=2)
            my_group.user_set.add(user)
            lawyer = Lawyer.objects.create(
                user=user, bar_number=lawyer_form.instance.bar_number, lawyer_status=lawyer_form.instance.lawyer_status)

            if team:
                lawyer_team=Team.objects.get(pk=team.pk)
                lawyer_team.lawyer.add(lawyer)

            messages.success(request, "Lawyer has been added")

            return HttpResponseRedirect(reverse('accounts:lawyer_detail', args=[lawyer.pk]))
        else:
            messages.error(request,user_form.errors)
            return redirect('accounts:lawyer_list')

    else:
        messages.error(request, "Lawyer could not be added")

        lawyer_form = LawyerForm()
        user_form = UserForm()

    return render(request, 'accounts/signup.html', {'user_form': user_form, 'lawyer_form': lawyer_form})


@login_required
def lawyer_list(request):
    lawyers = Lawyer.objects.all()
    user_form = UserForm(request.POST or None)
    lawyer_form = LawyerForm(request.POST or None)
    context = {
        'lawyers': lawyers,
        'lawyer_form': lawyer_form,
        'user_form': user_form
    }

    return render(request, 'accounts/lawyers.html', context)


@login_required
def lawyer_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    all_team = Team.objects.filter(team_leader__user = request.user)
    lawyer = get_lawyer(user)
    user_form = LawyerProfileForm(request.POST or None, instance=request.user)
    lawyer_form = LawyerForm(request.POST or None, instance=lawyer)
    cases = Case.objects.filter(lawyer=lawyer)
    # cases = Case.objects.select_related('lawyer').filter(lawyer__user=user)
    print(cases)
    pending = Case.objects.filter(closed=False)
    completed = Case.objects.filter(closed=True)
    case_form = CaseForms()
    context = {
        'lawyer': lawyer,
        'user_form': user_form,
        'lawyer_form': lawyer_form,
        'cases': cases,
        'pending': pending,
        'completed': completed,
        'form': case_form,
        'p_form': PrinciplesForm(request.POST or None),
        'all_team':all_team,
    }

    return render(request, 'accounts/lawyer-profile.html', context)


@login_required
def lawyer_detail(request, pk):
    lawyer = get_object_or_404(Lawyer, pk=pk)
    team=Team.objects.filter(lawyer=lawyer)[0]
    cases=Case.objects.filter(
            Q(team=team) | Q(lawyer =lawyer) )
    logs=LogEntry.objects.filter(user_id=lawyer.user.id)
    # cases = Case.objects.filter(lawyer=lawyer)lead_professional 
    pending = Case.objects.filter(lawyer=lawyer, closed=False)
    completed = Case.objects.filter(lawyer=lawyer, closed=True)
    user_form = StaffUpdateForm(request.POST or None, instance=lawyer.user)
    lawyer_form = LawyerForm(request.POST or None, instance=lawyer)

    print(cases)
    print(cases.count())
    context = {
        'lawyer': lawyer,
        'cases': cases,
        'pending': pending,
        'completed': completed,
        'user_form': user_form,
        'lawyer_form': lawyer_form,
        'logs':logs,
    }

    return render(request, 'accounts/lawyer_detail.html', context)


@login_required
def other_staff(request):
    staff_list = OtherStaff.objects.all()
    staff_form = OtherStaffForm()
    user_form = UserForm()

    context = {
        'staff_list': staff_list,
        'staff_form': staff_form,
        'user_form': user_form
    }

    return render(request, 'accounts/staff_list.html', context)


def get_status(id):
    qs = Status.objects.get(id=id)
    if qs:
        return qs
    else:
        return None


@login_required
def update_lawyer_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    lawyer = get_lawyer(user)
    if request.method == 'POST':

        user_form = LawyerProfileForm(
            request.POST or None, request.FILES or None, instance=request.user)
        lawyer_form = LawyerForm(request.POST or None, instance=lawyer)

        if user_form.is_valid() and lawyer_form.is_valid():
            user = user_form.save(commit=False)

            lawyer_form.instance.user = request.user

            user.save()
            lawyer_form.save()
            log_change(request.user.pk,user,"updated lawyer profile")
            messages.success(request, "profile has been updated")
            print("success")

            return HttpResponseRedirect(reverse('accounts:lawyer_profile', args=[user.pk]))

        else:
            print("failed")
            return HttpResponseRedirect(reverse('accounts:lawyer_profile', args=[user.pk]))

    else:

        user_form = LawyerProfileForm(
            request.POST or None, instance=request.user)
        lawyer_form = LawyerForm(request.POST or None, instance=lawyer)

    return render(request, "accounts/lawyer-profile.html", {'lawyer_form': lawyer_form, 'user_form': user_form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            log_change(request.user.pk,user,"changed password")
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('logout')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })


@login_required
def add_staff(request):

    if request.method == "POST":
        staff_form = OtherStaffForm(request.POST or None)
        user_form = UserForm(request.POST or None)

        if user_form.is_valid() and staff_form.is_valid():

            user = user_form.save(commit=False)
            team=user_form.cleaned_data['team']
            email = user_form.cleaned_data.get('email')
            password = user_form.cleaned_data.get('password1')
            email = user_form.cleaned_data.get('email')
            user.set_password(password)

            user.save()
            my_group = Group.objects.get(pk=1)
            my_group.user_set.add(user)

            staff_form.instance.user = user
            staff=staff_form.save()
            if team:

                staff_team=Team.objects.get(pk=team.pk)
                staff_team.support_staff.add(staff)

            add_log(request.user.pk,staff,"added a staff")
            messages.success(request,"user has been added")
            return redirect('accounts:staff_list')
        else:
            messages.error(request, user_form.errors)
            return redirect('accounts:staff_list')

    else:
        staff_form = OtherStaffForm()
        user_form = UserForm()

    return render(request, "accounts/add_staff.html", {'staff_form': staff_form, 'user_form': user_form})


@login_required
def staff_details(request, pk):
    staff = get_object_or_404(OtherStaff, pk=pk)
    user_form = StaffUpdateForm(instance=staff.user)
    staff_form = OtherStaffForm(instance=staff)

    logs=LogEntry.objects.filter(user_id=staff.user.id)

    
    team=Team.objects.filter(support_staff=staff)[0]
    cases=Case.objects.filter(
            Q(team=team) | Q(staff =staff) )




    doc = Document.objects.filter(added_by=staff.user)
    rec = DocumentRecord.objects.filter(approved_by=staff)
    print(rec)
    not_available = Document.objects.select_related(

accounts/templates/accounts/roles/role_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
Role Details
{% endblock title %}



{% block content %}
<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Lawyer System.</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'accounts:role_list' %}">Role List</a>
                            </li>
                            <li class="breadcrumb-item active">Role Details</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->
        {% include 'messages/messages.html' %}









        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="mt-0 header-title text-center">
                            {{role.title|title}}
                        </h2>
                  






                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->
            </div>
            <!--end col-->


            <div class="col-md-12 col-lg-4">
                <div class="card">
                    <div class="card-body">



                      
                        <center>
                            <h3>Actions</h3>
                        </center>
                        <center>
                            <button class="btn btn-primary" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-lg">Edit</button>

                        {% if user.is_superuser or user.is_staff %}

                        <button class="btn btn-danger" data-toggle="modal" data-animation="bounce"
                            data-target=".bs-example-modal-center">Delete</button>
                        </center>

                        {% endif %}




                    </div>
                    <!--end card-body-->
                </div>
                <!--end card-->
            </div>



            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0 text text-center" id="myLargeModalLabel">Edit Staff Role
                            </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        </div>
                        <div class="modal-body">



                            <form action="{% url 'accounts:update_role' role.pk %}" method="post">
                                {% csrf_token %}
                                {{form|crispy}}
                                {{form.erorrs}}
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>




            <div class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
                aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title mt-0" id="exampleModalLabel">Delete Staff Role </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are You Sure You Want To Delete {{role.title|title}}</p>


                           <center>
                                <a href="{% url 'accounts:delete_role' role.pk %}" type="submit" class="btn btn-danger">Delete</a>
                                 <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                               Close
                            </button>
                          </center>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div>

        </div>
    </div>
    {% endblock content %}

accounts/templates/accounts/roles/role_list.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% load crispy_forms_tags %}
{% block title %}
Role List


{% endblock title %}

{% block content %}


<div class="page-content">

    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="float-right">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Lawyer System.</a></li>

                            </li>
                            <li class="breadcrumb-item active">Role List</li>
                        </ol>
                    </div>

                </div>
                <!--end page-title-box-->
            </div>
            <!--end col-->
        </div>
        <!-- end page title end breadcrumb -->

        {% include 'messages/messages.html' %}








        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-body">
                        <button class="btn btn-gradient-primary px-4 float-right mt-0 mb-3" data-toggle="modal"
                            data-target=".bd-example-modal-xl"><i class="mdi mdi-plus-circle-outline mr-2"></i>Add New
                            Staff Role</button>

                        <h4 class="mt-0 header-title">Support Staff Roles</h4>

                        <div class="table-responsive dash-social">
                            <table id="datatable" class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Role</th>
                                      

                                        <th>Action</th>

                                    </tr>
                                </thead>


                                <!-- load -->


                                <tbody>

                                    {% for role in role_list %}
                                    <tr>

                                        <td>{{forloop.counter}}</td>
                                        <td> <a href="{% url 'accounts:role_detail' role.pk %}">{{role.title|title}}</a>
                                        </td>





                                        




                                        <td>

                                            <a href="{% url 'accounts:role_detail' role.pk %}"
                                                class="btn btn-gradient-secondary waves-effect waves-light"><i
                                                    class="mdi mdi-eye"></i></a>






                                        </td>

                                    </tr>



                                    {% endfor %}



                                    <!--end tr-->




                                </tbody>
                            </table>
                        </div>


                    </div>













                    <!-- sample modal content -->
                    <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-xl">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title mt-0" id="myModalLabel">New Staff Role</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">×</button>
                                </div>
                                <div class="modal-body">

                                    <form action="{% url 'accounts:add_role' %}" method="post">
                                        {% csrf_token %}
                                        {{form|crispy}}


                                        <center>
                                            <button type="submit" class="btn btn-secondary">Add Staff Role</button>
                                            <button type="button" class="btn btn-danger waves-effect"
                                                data-dismiss="modal">Close</button>


                                        </center>

                                </div>
                                </form>

                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->













            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

{% endblock content %}