accounts/urls.py
from django.urls import path
from .views import (accounts, update_lawyers_profile, staff_detail_view,
                    lawyer_profile_view, lawyer_detail, lawyer_list,
                    lawyer_profile, other_staff, update_lawyer_profile,
                    change_password, add_staff, staff_details,
                    update_staff, update_staff_profile, delete_lawyer, delete_staff,
                    client_dashboard,get_case_details ,team_list_view,add_team,
                    update_team,team_detail,team_update,delete_team,
                    add_role,role_detail,role_list,update_role,delete_role,
                    status_list,add_status,delete_status,update_status,status_detail,case_detail_acc,get_case_expenses,AccountExpense, account_expense,
                    invoice_list,invoice_detail,approve_invoice





                    )


app_name = "accounts"


urlpatterns = [

    path("accounts/signup", accounts, name="signup"),
    path("accounts/lawyer/signup", lawyer_profile_view, name='lawyer-signup'),
    path("accounts/lawyers/lawyer-list", lawyer_list, name="lawyer_list"),
    path("accounts/lawyers/<int:pk>/lawyer-detail",
         lawyer_detail, name="lawyer_detail"),


    path("accounts/lawyers/<int:pk>/lawyer-profile",
         lawyer_profile, name="lawyer_profile"),

    path("accounts/front-desk/staff-list", other_staff, name="staff_list"),
    path("accounts/password", change_password, name="change_password"),
    path("accounts/users/add-staff", add_staff, name="add_staff"),
    path("accounts/users/<int:pk>/staff-detail",
         staff_details, name='staff_detail'),
    path("accounts/users/<int:pk>/update-staff",
         update_staff, name='update_staff'),

    path("accounts/lawyers/<int:pk>/lawyers-profile",
         update_lawyers_profile, name="lawyers_profile"),







    path("accounts/profile/<int:pk>/update-profile",
         update_lawyer_profile, name="update_profile"),
    path("accounts/<int:pk>/profile/staff-profile",
         staff_detail_view, name="staff_profile"),


    path("accounts/profile/<int:pk>/update-staff-profile",
         update_staff_profile, name="staff_profileupdate"),

    path("accounts/lawyers/<int:pk>/delete",
         delete_lawyer, name="delete_lawyer"),
    path("accounts/staff/<int:pk>/delete", delete_staff, name="delete_staff"),

    ######################### CLIENTS ###############################################


    path("accounts/clients/<int:pk>/client-dashboard",client_dashboard,name="client_dashboard"),
    path("accounts/clients/<int:pk>/case-detail",get_case_details, name="case_details"),

    ############################################ TEAMS ##################################################

    path("accounts/teams/team-list",team_list_view,name='teams'),
    path("accounts/teams/add-team",add_team,name="add_team"),
    path("accounts/teams/<int:pk>/team/detail",team_detail,name="team_detail"),
    path("accounts/teams/<int:pk>/team/delete",delete_team, name="team_delete"),
    path("accounts/teams/<int:pk>/team/update",team_update,name="team_update"),
    path("accounts/teams/<int:pk>/team/update",update_team,name="update_team"),


    ############################# ROLES #######################################
    path("accounts/roles/roles-list",role_list,name='role_list'),
    path("accounts/roles/add-role",add_role,name='add_role'),

    path("accounts/roles/<int:pk>/role-details",role_detail,name="role_detail"),
    path("accounts/roles/<int:pk>/update-role",update_role,name="update_role"),
    path("accounts/roles/<int:pk>/delete-role",delete_role,name="delete_role"),


    ############################ Lawyer Status ###############################

    path("accounts/status/status-list",status_list,name='status_list'),
    path("accounts/expenses",account_expense,name='expenses'),
    path("accounts/status/add-status",add_status,name='add_status'),
    path("accounts/status/<int:pk>/status-details",status_detail,name="status_detail"),
    path("accounts/status/<int:pk>/update-status",update_status,name="update_status"),
    path("accounts/status/<int:pk>/delete-status",delete_status,name="delete_status"),
    path("accounts/cases/<int:pk>/detail",case_detail_acc,name='case_detail_acc'),
    path("accounts/cases/<int:pk>/case-expenses",get_case_expenses,name='case_expenses'),



     # invoice
     
    path("accounts/invoice_list/",invoice_list,name='invoice_list'),
    path("accounts/invoice_detail/<int:pk>",invoice_detail,name='invoice_detail'),
    path("accounts/approve_invoice/<int:pk>",approve_invoice,name='approve_invoice'),







]

cases/urls.py
from django.urls import path

from .views import (case_detail, add_case, update_case,
                    delete_case, add_task,upload_files,
                    new_case,  pending_list, completed_list, CaseList, CaseCreateView, CategoryListView,
                    delete_cat, cat_update, cat_add, add_argument, cat_detail, file_list,
                    delete_files, task_view, task_list_view, completed, delete_task, argument_list, argument_detail, arg_update, arg_delete, case_filter, complete_case,
                    court_list, add_court, court_detail, update_court, court_delete,

                    add_session, update_session, detail_session, delete_session,bill_case,

                    add_process, edit_task,generate_process,generate_process1,list_processes,process_detail,update_process,delete_process,add_to_archives,
                    upload_archives,update_archive,archive_detail,
                    add_action_report,list_action_reports,update_action,post_action_detail,delete_action,
                    add_rep,rep_detail,update_rep,delete_rep,rep_list,
                    case_history,
                    request_file,request_list,approve_request,make_request,all_files,start_timer,case_hours,
                    add_expense,ExpenseDetailView,ExpenseListView,update_expense,delete_expense,
                    RenumerationList,approve_renumeration,request_renumeration,
                    request_client_payment,update_client_payment,client_payment_list,client_payment_detail,edit_start_timer, addpercharge, PendingExpenseListView, accept_expense, 
                    decline_expense,resend_expense,generate_invoice_total, generate_invoice_total_save,calendar,all_user_logs,all_user_logs_per_case,upload_terms_files,terms_files_list,terms_edit

                    )


app_name = "cases"


urlpatterns = [

    path('cases/list/', CaseList.as_view(), name='case_list'),
    path('calendar/', calendar, name='calendar'),
    path('cases/list/filter-cases', case_filter, name='case_filter'),




    path("cases/pending-list", pending_list, name="pending_list"),

    path("cases/completed-list", completed_list, name="completed_list"),
    ############################### ARCHIVED CASES #####################################################
    path("cases/archived_cases", add_to_archives, name="add_archive"),
    path("cases/archives/<int:pk>/archive-details", archive_detail, name="archive_detail"),
    path("cases/archives/<int:pk>/update-archive",update_archive, name="archive_update"),
    path("cases/archives/<int:pk>/upload-files",upload_archives, name="archive_upload"),

    path("cases/<int:pk>/case-detail", case_detail, name="case_detail"),
    path("cases/add-case", add_case, name="add_case"),



    path("cases/<int:pk>/case-update", update_case, name="case_update"),
    path("cases/<int:pk>/case-delete", delete_case, name="case_delete"),
    path("cases/tasks/<int:pk>/add-task", add_task, name="add_task"),
    path("cases/files/<int:pk>/add-files", upload_files, name="upload_files"),




    ############################### TERMS OF ENGAGEMENT ########################################################
    path("cases/termsofengagement/<int:pk>/add-files", upload_terms_files, name="upload_terms_files"),
    path("cases/termsofengagement/<int:pk>/list-files", terms_files_list, name="terms_files_list"),
    path("cases/termsofengagement/terms_edit", terms_edit, name="terms_edit"),



    ############################### CATEGORY ########################################################
    path("cases/category/list", CategoryListView.as_view(), name="cat_list"),
    path("cases/category/<int:pk>/update",
         cat_update, name="cat_update"),
    path("cases/category/<int:pk>/delete", delete_cat, name="cat_delete"),
    path("cases/category/add", cat_add, name="cat_add"),
    path("cases/argument/<int:pk>/add", add_argument, name="add_arg"),
    path("cases/category/<int:pk>/detail", cat_detail, name="cat_detail"),
    path("cases/<int:pk>/case-files", file_list, name="file_list"),
    path("cases/<int:pk>/delete_file", delete_files, name="delete_file"),
    path("cases/tasks/<int:pk>/list", task_view, name="task_list"),
    path("cases/tasks/<int:pk>/list-tasks", task_list_view, name="list_tasks"),
    path("cases/tasks/<int:pk>/completed", completed, name="completed"),
    path("cases/tasks/<int:pk>/delete", delete_task, name="delete_task"),
    path("cases/<int:pk>/legal_arguments/list",
         argument_list, name="argument_list"),
    path("cases/<int:pk>/legal_arguments/detail",
         argument_detail, name="argument_detail"),
    path("cases/<int:pk>/legal_arguments/update",
         arg_update, name="argument_update"),
    path("cases/<int:pk>/legal_arguments/delete",
         arg_delete, name="argument_delete"),

    path("cases/<int:pk>/case-update-status",
         complete_case, name="complete_case"),
    ########################################################## COURT ######################################################################
    path('cases/courts/list', court_list, name='court_list'),
    path('cases/courts/<int:pk>/court-detail',
         court_detail, name="court_detail"),
    path('cases/courts/<int:pk>/court-update',
         update_court, name="court_update"),
    path('cases/courts/add', add_court, name="court_add"),
    path('cases/courts/<int:pk>/court-delete',
         court_delete, name="court_delete"),

    #################################################### COURT SESSIONS #################################################################


    path('cases/court-sessions/<int:pk>/add', add_session, name="session_add"),
    path('cases/court-sessions/<int:pk>/details',
         detail_session, name="session_detail"),
    path('cases/court-sessions/<int:pk>/update',
         update_session, name="session_update"),
    path('cases/court-sessions/<int:pk>/delete',
         delete_session, name="session_delete"),


    ############################################### PROCESSES ####################################
    path('cases/processes/add', add_process, name="process_add"),
    path('cases/processes/list', list_processes, name="list_process"),

    path('cases/processes/<int:pk>/generate-process', generate_process1, name="generate_process"),
    path('cases/processes/<int:pk>/process-detail', process_detail, name="process_detail"),
    path('cases/processes/<int:pk>/process-update', update_process, name="process_update"),
    path('cases/processes/<int:pk>/delete-process', delete_process, name="process_delete"),



    ############################################### BILL CASE ####################################
    path('cases/<int:pk>/bill-case',bill_case,name='bill_case'),

    path('cases/tasks/<int:pk>/edit-task',edit_task,name='edit_task'),

    ############################################### POST ACTION REPORT ##########################
    path('cases/post-action-report/<int:pk>/add-new',add_action_report,name="add_action"),
    path('cases/post-action-report/<int:pk>/report-list',list_action_reports,name='list_report'),
    path('cases/post-action-report/<int:pk>/report-detail',post_action_detail,name="action_detail"),
    path('cases/post-action-report/<int:pk>/update-report',update_action,name='action_update'),
    path('cases/post-action-report/<int:pk>/delete-report',delete_action,name='action_delete'),

##################################### REPRESENTATION ############################################
    path('cases/representation/add',add_rep,name="add_rep"),
    path('cases/representation/list',rep_list,name="rep_list"),
    path('cases/representation/<int:pk>/details',rep_detail,name="rep_detail"),
    path('cases/representation/<int:pk>/update',update_rep,name="update_rep"),
    path('cases/representation/<int:pk>/delete',delete_rep,name="delete_rep"),
    path("cases/<int:pk>/case-history",case_history,name='case_history'),



    ################################### ARCHIVE REQUESTS #########################################
    path('cases/archives/request',request_file,name='request_file'),
    path('cases/archives/requests/list',request_list,name='request_list'),
    path('cases/archives/<int:pk>/request',make_request,name='make_request'),
    path('cases/archives/<int:pk>/request/approve',approve_request,name='approve_request'),

    ################################### CASE FILES ###############################################
    path('cases/files/all-files',all_files,name="all_files"),
    path('cases/start-timer',start_timer,name="start_timers"),
    path('cases/edit_start_timer',edit_start_timer,name="edit_start_timer"),
    path('cases/<int:pk>/timer/elapsed-time',case_hours,name="case_hours"),
    path('cases/addpercharge',addpercharge,name="addpercharge"),
    path('cases/delete_case/<int:pk>',delete_case,name="delete_case"),


     ################################## EXPENSES #################################################
    path('cases/expenses/', ExpenseListView.as_view(), name='expenses'),
    path('cases/pending_expenses/', PendingExpenseListView.as_view(), name='pending_expenses'),
    path('cases/expenses/<int:pk>/detail', ExpenseDetailView.as_view(), name='expense_detail'),
    path('cases/expenses/<int:pk>/update', update_expense, name='update_expense'),
    path('cases/expenses/<int:pk>/delete', delete_expense, name='delete_expense'),
    path('cases/expenses/add-expense',add_expense,name='add_expense'),
    path('cases/accept_expense/<int:pk>',accept_expense,name='accept_expense'),
    path('cases/decline_expense/<int:pk>',decline_expense,name='decline_expense'),
    path('cases/resend_expense/<int:pk>',resend_expense,name='resend_expense'),

    ################################### Renumeration #############################################
    path('case/renumeration/list',RenumerationList.as_view(),name='renumerations'),
    path('case/renumeration/<int:pk>/approve',approve_renumeration,name='approve_renumeration'),

firm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, FirmChart,user_path,my_notifications,my_custom_page_not_found_view,mark_as_deleted,mark_as_read,mark_as_unread,user_logs,all_read,all_unread,account_dash,go_to_target, view_team_logs
# from ajax_select import urls
# from ajax_select import urls as ajax_select_url
from ajax_select import urls as ajax_select_urls


admin.autodiscover()

handler404 = 'firm.views.my_custom_page_not_found_view'

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", index, name="index"),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('django.contrib.auth.urls')),
    path("api/chart/data", FirmChart.as_view(), name="api-data"),
    path("user_path/redirect/", user_path, name="user_path"),
    path("user-notifications/", my_notifications, name="user_notifications"),
    path("go_to_target/<int:pk>", go_to_target, name="go_to_target"),
    path("", include('accounts.urls')),
    path("", include('cases.urls')),
    path("", include('documents.urls')),
    path("", include('principles.urls')),
    path("", include('clients.urls')),
    path("", include('schedules.urls')),
    path("", include('visitors.urls')),
    path("", include('wills.urls')),
    path("", include('correspondents.urls')),
    path('comment/', include('comment.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('notifications/', include('notify.urls', 'notifications')),
    path("resources/", include('resources.urls')),
    path("activity/<int:pk>/user-logs",user_logs,name='user-logs'),
    path('ajax_select/', include(ajax_select_urls)),
    path('user-notifications/<int:pk>/read',mark_as_read,name="read"),
    path('user-notifications/<int:pk>/unread',mark_as_unread,name="unread"),
    path('user-notifications/all-read',all_read,name="all_read"),
    path('user-notifications/all-unread',all_unread,name="all_unread"),
    path("account_dash/",account_dash,name='account_dash'),
    path("view_team_logs/",view_team_logs,name='view_team_logs'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),







]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/firm/index.html
{% extends 'base.html' %}
{% load static %}

{% load auth_extras %}


{% block content %}



<!-- Page Content-->
<div class="page-content">

  <div class="container-fluid">
  {% if request.user|has_group:'Lawyer' or request.user|has_group:'Staff' or request.user.is_superuser %}

    <!-- Page-Title -->
    <div class="row">
      <div class="col-sm-12">
        <div class="page-title-box">
          <div class="float-right">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="javascript:void(0);">Lawyer System. </a></li>

            </ol>
          </div>
          <!-- <h4 class="page-title">Customers</h4> -->
        </div>
        <!--end page-title-box-->
      </div>
      <!--end col-->
    </div>
    <!-- end page title end breadcrumb -->

    <div class="row">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <div class="icon-contain">
              <div class="row">
                <div class="col-8 align-self-center">
                  {% if user.is_superuser %}
                  <h5 class=""> <a href="{% url 'accounts:lawyer_list' %}">All Lawyers</a> </h5>
                  <p class="text mb-0"> <a href="{% url 'accounts:lawyer_list' %}">{{lawyer_count}}</a> <i
                      class="mdi mdi-menu-up text-success font-16"></i></p>
                  {% else %}
                  <h5 class="">All Lawyers</h5>
                  <p class="text mb-0">{{lawyer_count}} <i class="mdi mdi-menu-up text-success font-16"></i></p>
                  {% endif %}

                </div>
                <!--end col-->
                <div class="col-4 drop-shadow">
                  <span class="peity-bar" data-peity='{ "fill": ["#e0e7fd", "#4d79f6"]}' data-width="100%"
                    data-height="60">6,2,8,4,3,8,1,3,6,5,9,2,8,1,4,8,9,8,2,1</span>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end icon-contain-->
          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>
      <!--end col-->
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <div class="icon-contain">
              <div class="row">
                <div class="col-8 align-self-center">
                  <h5 class=""><a href="{% url 'cases:case_list' %}">All Cases</a></h5>
                  <p class="text mb-0"> <a href="{% url 'cases:case_list' %}">{{case.count}}</a> <i
                      class="mdi mdi-menu-down text-danger font-16"></i></p>
                </div>
                <!--end col-->
                <div class="col-4 drop-shadow">
                  <span class="peity-line" data-width="100%" data-peity='{ "fill": ["#c3f0ff"],"stroke": ["#4ac7ec"]}'
                    data-height="60">6,2,8,4,3,8,1,3,6,5,9,2,8,1,4,8,9,8,2,1</span>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end icon-contain-->
          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>
      <!--end col-->
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <div class="icon-contain">
              <div class="row">
                <div class="col-8 align-self-center">
                  <h5 class=""><a href="{%url 'cases:all_user_logs'%}">User Activities</a></h5>
                  <p class="text mb-0"> <a href="{%url 'cases:all_user_logs'%}">{{logs_count}}</a> <i
                      class="mdi mdi-menu-up text-success font-16"></i></p>
                </div>
                <!--end col-->
                <div class="col-4 text-right drop-shadow">
                  <span class="peity-donut "
                    data-peity='{ "fill": ["#4d79f6", "#e0e7fd"], "innerRadius": 23, "radius": 32 }' data-width="60"
                    data-height="60">226,134</span>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end icon-contain-->
          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>
      <!--end col-->
    </div>

    {% else %}
{% endif %}
    <div class="row">
      <div class="col-lg-12 col-xl-8">
        <div class="card">
          <div class="card-body">
            <h4 class="mt-0 header-title">Cases</h4>
            <!-- <p class="text-muted mb-3 d-inline-block text-truncate w-100">Polar area charts are similar to pie
              charts, but each segment has the same angle - the radius of the segment
              differs depending on the value.
            </p> -->
            <canvas id="myChart" class="drop-shadow" height="142"> </canvas>
            <!-- <canvas id="myChart2" class="drop-shadow" height="300"> </canvas> -->

          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>
















      <link href="{% static 'calender/jkm/main.css'%}" rel='stylesheet' />
    <script src="{% static 'calender/jkm/main.js'%}"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar1');
        var today = new Date();

        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev',
            center: 'title',
            right: 'next',
          },
          initialDate: today,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          select: function(arg) {
            console.log('clicked')
            var modal = document.getElementById('eventModal')
            modal.style.display = 'block'
            calendar.unselect()
          },
          // THIS KEY WON'T WORK IN PRODUCTION!!!
          // To make your own Google API key, follow the directions here:
          // http://fullcalendar.io/docs/google_calendar/
          // googleCalendarApiKey: 'AIzaSyCqCxjjLtjbtkX37aOtWB8OfwBLy_6QuYk',

          // bangladesh Holidays
          // events: 'bn.bd#holiday@group.v.calendar.google.com',
          eventClick: function(arg) {
            if (arg.event.id) {
              events = arg.event.id
              window.location.replace("{% url 'cases:edit_task' pk=456674353465678878754 %}".replace('456674353465678878754', events))
            }
          },
          editable: true,
          dayMaxEvents: true, // allow "more" link when too many events
          events: {{ events|safe }},
          // events: [
          //   {
          //     title: 'All Day Event',
          //     start: '2021-06-26'
          //   },
          //   {
          //     groupId: 999,
          //     title: 'Repeating Event',
          //     start: '2020-09-16T16:00:00'
          //   },
          //   {
          //     title: 'Conference',
          //     start: '2020-09-11',
          //     end: '2020-09-13'
          //   },
          //   {
          //     title: 'Click for Google',
          //     url: 'http://google.com/',
          //     start: '2020-09-28'
          //   }
          // ]
        });

        calendar.render();
      });
    
  </script>


      <div class="col-lg-12 col-xl-4">
        <div class="card">
          <div class="card-body">
            <h4 class="mt-0 header-title"><a href="{%url 'cases:calendar'%}">Calendar</a> </h4>
             <!-- <p class="text-muted mb-3 d-inline-block text-truncate w-100">Polar area charts are similar to pie
              charts, but each segment has the same angle - the radius of the segment
              differs depending on the value......
            </p> -->
            <div id='calendar1'></div>

          </div>
          <!--end card-body-->
        </div>
        <!--end card-->
      </div>




      <!--end col-->
    </div>
    <!--end row-->

    <!--end row-->

    {% if request.user|has_group:"Lawyer" %}

    <div class="row">
      
      <!--end col-->

      <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-body">

                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Cases</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#profile" role="tab">User Activities(Logs)</a>
                    </li>                                                
                    <!-- <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#settings" role="tab">Settings</a>
                    </li> -->
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active p-3" id="home" role="tabpanel">
                      <table id="datatable" class="table">
                        <thead class="thead-light">
                          <tr>
                            <th>Case Title</th>
                            <th>Category</th>
                            <th>Status</th>
                            <th>Date Added</th>
                            <th>Added By</th>
        
        
                            <th>Action</th>
                          </tr>
                          <!--end tr-->
                        </thead>
        
                        {% include 'cases/snippets/list.html' with cases=case %}
                      </table>
                    </div>
                    <div class="tab-pane p-3" id="profile" role="tabpanel">
                      <table id="datatable" class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>User</th>


                                <th>Action</th>
                                <th> Date</th>


                            </tr>
                            <!--end tr-->
                        </thead>
                        <tbody>
                    {% if logs %}
                    {% for log in logs %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{log.user}}</td>
                        <td>{{log.change_message|title}} {{log.object_repr|title}}</td>
                        <td>{{log.action_time}}</td>
                    </tr>
                        

                    {% endfor %}
                    {% endif %}
                </tbody>
                    </table>
                    </div>                                                
                    <!-- <div class="tab-pane p-3" id="settings" role="tabpanel">
                        <p class="text-muted mb-0">
                            Trust fund seitan letterpress, keytar raw denim keffiyeh etsy.
                        </p>
                    </div> -->
                </div>        
            </div><!--end card-body-->
        </div><!--end card-->
    </div><!--end col-->
    </div>
    <!--end row-->

    {% endif %}

  </div><!-- container -->

  {% endblock content %}